/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIndexRouteImport } from './routes/quiz/index'
import { Route as MemoryIndexRouteImport } from './routes/memory/index'
import { Route as DndIndexRouteImport } from './routes/dnd/index'
import { Route as QuizTestRouteImport } from './routes/quiz/test'
import { Route as QuizResultsWolfIdRouteImport } from './routes/quiz/results/$wolfId'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryIndexRoute = MemoryIndexRouteImport.update({
  id: '/memory/',
  path: '/memory/',
  getParentRoute: () => rootRouteImport,
} as any)
const DndIndexRoute = DndIndexRouteImport.update({
  id: '/dnd/',
  path: '/dnd/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizTestRoute = QuizTestRouteImport.update({
  id: '/quiz/test',
  path: '/quiz/test',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizResultsWolfIdRoute = QuizResultsWolfIdRouteImport.update({
  id: '/quiz/results/$wolfId',
  path: '/quiz/results/$wolfId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/quiz/test': typeof QuizTestRoute
  '/dnd': typeof DndIndexRoute
  '/memory': typeof MemoryIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/quiz/results/$wolfId': typeof QuizResultsWolfIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/quiz/test': typeof QuizTestRoute
  '/dnd': typeof DndIndexRoute
  '/memory': typeof MemoryIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/quiz/results/$wolfId': typeof QuizResultsWolfIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/quiz/test': typeof QuizTestRoute
  '/dnd/': typeof DndIndexRoute
  '/memory/': typeof MemoryIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/quiz/results/$wolfId': typeof QuizResultsWolfIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/quiz/test'
    | '/dnd'
    | '/memory'
    | '/quiz'
    | '/quiz/results/$wolfId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/quiz/test'
    | '/dnd'
    | '/memory'
    | '/quiz'
    | '/quiz/results/$wolfId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/quiz/test'
    | '/dnd/'
    | '/memory/'
    | '/quiz/'
    | '/quiz/results/$wolfId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  QuizTestRoute: typeof QuizTestRoute
  DndIndexRoute: typeof DndIndexRoute
  MemoryIndexRoute: typeof MemoryIndexRoute
  QuizIndexRoute: typeof QuizIndexRoute
  QuizResultsWolfIdRoute: typeof QuizResultsWolfIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/': {
      id: '/memory/'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dnd/': {
      id: '/dnd/'
      path: '/dnd'
      fullPath: '/dnd'
      preLoaderRoute: typeof DndIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/test': {
      id: '/quiz/test'
      path: '/quiz/test'
      fullPath: '/quiz/test'
      preLoaderRoute: typeof QuizTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/results/$wolfId': {
      id: '/quiz/results/$wolfId'
      path: '/quiz/results/$wolfId'
      fullPath: '/quiz/results/$wolfId'
      preLoaderRoute: typeof QuizResultsWolfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  QuizTestRoute: QuizTestRoute,
  DndIndexRoute: DndIndexRoute,
  MemoryIndexRoute: MemoryIndexRoute,
  QuizIndexRoute: QuizIndexRoute,
  QuizResultsWolfIdRoute: QuizResultsWolfIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
